export const ActionTypes = {
  SET_PAGES: "SET_PAGES",
  FETCH_PAGES: "FETCH_PAGES",
  SET_PREMIUIM_OFFERS: "SET_PREMIUIM_OFFERS",
  FETCH_SECTIONS: "FETCH_SECTIONS",
  SET_SECTIONS: "SET_SECTIONS",
  REMOVE_SELECTED_SECTION: "REMOVE_SELECTED_SECTION"
};
